// Generated by CoffeeScript 1.6.2
(function() {
  var authKey, pubnub;

  authKey = process.argv[2];

  pubnub = require('./pubnub').init({
    subscribe_key: 'sub-c-4c15a542-ced1-11e2-b70f-02ee2ddab7fe',
    publish_key: 'pub-c-4268517d-1e7a-4bdd-8037-090a3c76a1f0',
    secret_key: process.argv[2],
    auth_key: authKey,
    origin: 'pam-beta.pubnub.com'
  });

  console.log("Granting read-only access to chat channel");

  pubnub.grant({
    channel: 'chat',
    read: true,
    write: false,
    callback: function(message) {
      return console.log("Successfully made grant request", message);
    },
    error: function(message) {
      return console.log("[ERROR] On grant request", message);
    }
  });

  console.log("Granting access for authentication channel");

  pubnub.grant({
    channel: 'authentication',
    read: false,
    write: true,
    callback: function(message) {}
  });

  console.log("Granting access for self on auth");

  pubnub.grant({
    channel: 'authentication',
    auth_key: authKey,
    read: true,
    write: true,
    callback: function(message) {}
  });

  console.log("Listening for logins and logouts");

  pubnub.subscribe({
    channel: 'authentication',
    callback: function(message) {
      message = JSON.parse(message);
      console.log("Got message on auth channel", message);
      if (message.action === 'login') {
        console.log("Logging in " + message.authKey);
        return pubnub.grant({
          channel: 'chat',
          read: true,
          write: true,
          auth_key: message.authKey,
          ttl: 1,
          callback: function() {
            return pubnub.publish({
              channel: message.authKey,
              message: JSON.stringify({
                action: 'login',
                success: true
              })
            });
          },
          error: function() {
            return pubnub.publish({
              channel: message.authKey,
              message: JSON.stringify({
                action: 'login',
                success: false
              })
            });
          }
        });
      } else if (message.action === 'logout') {
        console.log("Logging out " + message.authKey);
        return pubnub.grant({
          channel: 'chat',
          read: true,
          write: false,
          auth_key: message.authKey,
          callback: function() {
            return pubnub.publish({
              channel: message.authKey,
              message: JSON.stringify({
                action: 'logout',
                success: true
              })
            });
          },
          error: function() {
            return pubnub.publish({
              channel: message.authKey,
              message: JSON.stringify({
                action: 'logout',
                success: false
              })
            });
          }
        });
      } else if (message.action === 'presence') {
        console.log("Allowing presence for " + message.uuid);
        pubnub.grant({
          channel: message.uuid,
          read: true,
          write: false,
          auth_key: message.uuid,
          callback: function() {}
        });
        return pubnub.grant({
          channel: message.uuid,
          read: false,
          write: true,
          auth_key: authKey,
          callback: function() {}
        });
      }
    }
  });

}).call(this);
